id = "houston"
name = "Houston"
description = "A dark theme inspired by Astro's Houston VS Code theme"
version = "1.0.0"
schema_version = 1
authors = ["Sami Baadarani"]
repository = "https://github.com/sami-baadarani/zed-houston-theme"

[themes]
houston = "themes/houston.json"